### PR TITLE
Added support for Travis as a CIService

### PR DESCRIPTION
**Pull request by Aaron1011**

### CODE REVIEW

**Comment by redhotvengeance** [comment]
@Aaron1011 Sorry for the delayed response - the holidays are a busy time :)

This looks awesome - I dig Travis support!

Part of Deep Thought's core design is to be plugin-based - I want it to be flexible and fit to the needs of individuals/companies. For that reason, I'd like to avoid avoid having a lot of built-in deployers/CI services, because it would make deployer and CI service additions/updates dependent on new versions of the Deep Thought core lib. (It's true that the shell deployer and Janky CI service _are_ built-in, but I only did that so Deep Thought was usable out-of-box.)

Could you port this Travis CI service into its own gem and then add it to the [list of CI services](https://github.com/redhotvengeance/deep_thought/wiki/CI-Services) in the Deep Thought wiki? I just made a [CI service template](https://github.com/redhotvengeance/deep_thought-ci_service_plugin) that can be easily used as a starting point.

Let me know if you have any issues.

Thanks!

**Comment by Aaron1011** [comment]
@redhotvengeance: Would you like me to keep the name in the format `deep_though-#{name}_plugin` (e.g. `deep_though-travis_plugin`)?

**Comment by Aaron1011** [comment]
@redhotvengeance: I've added it to the wiki.

**Comment by redhotvengeance** [comment]
@Aaron1011 It doesn't really matter much. I didn't use "plugin" in the names of the [deployers](https://github.com/redhotvengeance/deep_thought/wiki/Deployers), but it's your gem, so it's really up to you.

The more important thing is that the plugin exists. It looks great - thanks for contributing!

**Pull request closed without merging**
